### ISSUE TITLE
I can't install this extension using the link provided in documentation

### ISSUE THREAD

**Issue by kgolubic** [collabnix/memgraph-docker-extension#2]
I tried to install this extension using the link https://open.docker.com/extensions/marketplace?extensionId=ajeetraina/memgraph-docker-extension&tag=latest that I found at https://collabnix.com/5-minutes-to-memgraph-using-memgraph-docker-extension/.

When I click the link Docker Desktop returns me an error that Authorization has failed.

![image](https://user-images.githubusercontent.com/46486712/217812186-d3225c9c-46f0-4435-8c28-3dd82133b98a.png)

**Comment by collabnix** [comment]
@kgolubic Can you try it now? I just pushed the latest version to Docker Hub.
Also, Please note that this is not yet validated by the Docker team.

**Comment by kgolubic** [comment]
@collabnix yes, it works now. I had to invoke install procedure twice but it showed up. Thank you!

**Comment by collabnix** [comment]
@kgolubic It's not a full-fledged Extension tbh but just an embedded UI.
I would love to see if you and your team can work on it and submit it to the Marketplace.
Happy to connect and help you understand the process. LMK.

**Comment by kgolubic** [comment]
Issue is resolved.
